{
 "title": "User service-2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ingress latency, ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.5 Q"
    },
    {
     "expr": "histogram_quantile(0.95, (sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.95 Q"
    },
    {
     "expr": "histogram_quantile(0.99, (sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.99 Q"
    }
   ]
  },
  {
   "title": "Latency, ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum(rate(app_request_latency_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.5 Q"
    },
    {
     "expr": "histogram_quantile(0.95, (sum(rate(app_request_latency_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.95 Q"
    },
    {
     "expr": "histogram_quantile(0.99, (sum(rate(app_request_latency_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "0.99 Q"
    }
   ]
  },
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Ingress status code 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Status code 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(app_5xx_error_count[1m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Ingress latency MAX, ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, (sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Latency MAX, ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, (sum(rate(app_request_latency_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"} != 0"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 34 },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio != 0"
    }
   ]
  }
 ]
}