{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
  {{- include "user-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "user-chart.fullname" . }}
  selector:
    matchLabels:
  {{- include "user-chart.labels" . | nindent 6 }}
  endpoints:
    - interval: 3s
      port: web
      path: /metrics
  {{- end }}